@echo off
chcp 65001 > nul
echo Organizando pastas do Agente SYNTROPY...

if not exist "RELATORIOS_E_ANALISES" mkdir "RELATORIOS_E_ANALISES"
if not exist "HABILIDADES_DO_AGENTE" mkdir "HABILIDADES_DO_AGENTE"
if not exist "FLUXOS_OPERACIONAIS" mkdir "FLUXOS_OPERACIONAIS"
if not exist "REGISTROS_DO_SISTEMA" mkdir "REGISTROS_DO_SISTEMA"
if not exist "DOCUMENTOS_DO_NUCLEO" mkdir "DOCUMENTOS_DO_NUCLEO"

echo Movendo Relatorios...
move "ANALISE_ARQUITETURA_SERVICE_FIRST.md" "RELATORIOS_E_ANALISES\" > nul
move "ANALISE_PLANO_GLOBAL_EDUCACIONAL.md" "RELATORIOS_E_ANALISES\" > nul
move "ANALISE_PLANO_MENTE_COLETIVA.md" "RELATORIOS_E_ANALISES\" > nul
move "ANALISE_PROTOCOLO_ANDAIMENTO_COGNITIVO.md" "RELATORIOS_E_ANALISES\" > nul
move "PLANO_DE_ACAO_IMPLANTACAO_INTEGRAL.md" "RELATORIOS_E_ANALISES\" > nul
move "RELATORIO_GERAL_SISTEMA_SINERGIA_V2.md" "RELATORIOS_E_ANALISES\" > nul
move "RELATORIO_HABILIDADES_SISTEMA_SINERGIA.md" "RELATORIOS_E_ANALISES\" > nul
move "RELATORIO_PRINCIPIOS_REGRAS_SISTEMA.md" "RELATORIOS_E_ANALISES\" > nul
move "RELATORIO_TECNICO_SISTEMA_SINERGIA.md" "RELATORIOS_E_ANALISES\" > nul
move "RESPOSTA_PARECER_TECNICO_AUDITORIA_V2.md" "RELATORIOS_E_ANALISES\" > nul

echo Movendo Habilidades...
move "SKILL_ANDAIMES_DINAMICOS.md" "HABILIDADES_DO_AGENTE\" > nul
move "SKILL_ENGENHARIA_RELACOES.md" "HABILIDADES_DO_AGENTE\" > nul
move "SKILL_ESPELHO_AFETIVO.md" "HABILIDADES_DO_AGENTE\" > nul
move "SKILL_EVANGELIZACAO.md" "HABILIDADES_DO_AGENTE\" > nul
move "SKILL_FILTRO_SEMANTICO.md" "HABILIDADES_DO_AGENTE\" > nul
move "SKILL_GESTAO_MEMORIA.md" "HABILIDADES_DO_AGENTE\" > nul
move "SKILL_HIVE_SYNC.md" "HABILIDADES_DO_AGENTE\" > nul
move "SKILL_LOCAL_FIRST.md" "HABILIDADES_DO_AGENTE\" > nul
move "SKILL_PBL_ENGINE.md" "HABILIDADES_DO_AGENTE\" > nul
move "SKILL_PEDAGOGIA_SISTEMICA.md" "HABILIDADES_DO_AGENTE\" > nul
move "SKILL_SENCIENCIA_CONTEXTUAL.md" "HABILIDADES_DO_AGENTE\" > nul
move "SKILL_TRAINING_COACH.md" "HABILIDADES_DO_AGENTE\" > nul

echo Movendo Fluxos...
move "WORKFLOW_SINERGIA_OPERACIONAL.md" "FLUXOS_OPERACIONAIS\" > nul

echo Movendo Registros...
move "STATUS_UPDATE.md" "REGISTROS_DO_SISTEMA\" > nul
move "MEMORY_STATUS.md" "REGISTROS_DO_SISTEMA\" > nul
move "MESSAGE_TO_USER.md" "REGISTROS_DO_SISTEMA\" > nul
move "COMPLETED.md" "REGISTROS_DO_SISTEMA\" > nul
move "DONE.md" "REGISTROS_DO_SISTEMA\" > nul

echo Movendo Documentos do Nucleo...
move "Regras.md" "DOCUMENTOS_DO_NUCLEO\" > nul

echo Organizacao concluida!
pause
